-- Generated by tools/export_timescale_layer.py
CREATE EXTENSION IF NOT EXISTS timescaledb;

SELECT
    create_hypertable(
        'oraculo.metrics_series',
        'event_time',
        if_not_exists => TRUE
    );
